version: '3.7'

services:
  telebot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - ./.env
    depends_on:
      - telebot_db
  telebot_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql123
      - POSTGRES_DB=busbot

volumes:
  postgres_data: